#--------------------------------------------------------------------
#       Locale & Server
#--------------------------------------------------------------------
quarkus.default-locale=it-IT
quarkus.http.root-path=/api
quarkus.http.port=8080

#--------------------------------------------------------------------
#       Database (PostgreSQL su Docker)
#--------------------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:54321/postgres
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

#--------------------------------------------------------------------
#       Ebean (Il cuore del BE)
#--------------------------------------------------------------------
ebean.ddl.generate=true
ebean.ddl.run=true

#--------------------------------------------------------------------
#       CORS (Fondamentale per Svelte)
#--------------------------------------------------------------------
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

#--------------------------------------------------------------------
#       OpenAPI (Swagger per testare le API)
#--------------------------------------------------------------------
quarkus.smallrye-openapi.path=/docs/openapi
quarkus.swagger-ui.path=/docs/swagger
quarkus.swagger-ui.always-include=true

#--------------------------------------------------------------------
#       Flyway
#--------------------------------------------------------------------
quarkus.flyway.locations=dbinit
quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.ignore-missing-migrations=true
quarkus.flyway.clean-at-start=true
quarkus.flyway.clean-disabled=false

#--------------------------------------------------------------------
#       Logs
#--------------------------------------------------------------------
quarkus.log.level=INFO
quarkus.log.category."it.giupp".level=DEBUG

#--------------------------------------------------------------------
#       Live-reload
#--------------------------------------------------------------------
quarkus.live-reload.instrumentation=false