-- apply changes
create table game (
  id                            bigint generated by default as identity not null,
  lunghezza_selezionata_della_parola integer not null,
  tentativi_massimi             integer not null,
  parola_id                     bigint,
  stato_partita                 integer not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint ck_game_stato_partita check ( stato_partita in (0,1,2)),
  constraint uq_game_parola_id unique (parola_id),
  constraint pk_game primary key (id)
);

create table parola (
  id                            bigint generated by default as identity not null,
  lunghezza                     integer not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  valore                        varchar(255) not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_parola primary key (id)
);

create table risultato_lettera (
  id                            bigint generated by default as identity not null,
  tentativo_id                  bigint not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  lettera                       varchar(255) not null,
  stato                         varchar(8) not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint ck_risultato_lettera_stato check ( stato in ('CORRETTA','PRESENTE','ASSENTE')),
  constraint pk_risultato_lettera primary key (id)
);

create table tentativo (
  id                            bigint generated by default as identity not null,
  game_id                       bigint not null,
  numero_tentativo              integer not null,
  _version                      bigint not null,
  _data_creazione               timestamptz not null,
  _data_modifica                timestamptz not null,
  _utente_creazione             varchar(255) not null,
  _utente_modifica              varchar(255) not null,
  constraint pk_tentativo primary key (id)
);

-- foreign keys and indices
alter table game add constraint fk_game_parola_id foreign key (parola_id) references parola (id) on delete restrict on update restrict;

create index ix_risultato_lettera_tentativo_id on risultato_lettera (tentativo_id);
alter table risultato_lettera add constraint fk_risultato_lettera_tentativo_id foreign key (tentativo_id) references tentativo (id) on delete restrict on update restrict;

create index ix_tentativo_game_id on tentativo (game_id);
alter table tentativo add constraint fk_tentativo_game_id foreign key (game_id) references game (id) on delete restrict on update restrict;

